name: Deploy on Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Java application and run test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run unitary test
      run: mvn -B -Dtest=BookServiceUnitaryTest test
    - name: Run REST test
      run: mvn -B -Dtest=RestTest test
    - name: Run e2e test
      run: mvn -B -Dtest=SeleniumTest test
    - name: Build native with Maven
      run: mvn -B package -DskipTests
    - name: Upload jar for next job
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target

  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download Jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Generate tag
        run: echo ::set-output name=tag::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
        id: project
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/library:${{ steps.project.outputs.tag }} .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/library:${{ steps.project.outputs.tag }}

  publish_in_heroku_registry:
    name: Publish in Heroku Registry
    runs-on: ubuntu-latest
    needs: [build]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download Jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Build Docker Image
        run: docker build -t items .
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Change image name to point to Heroku registry
        run: docker tag items registry.heroku.com/$HEROKU_APP/web
      - name: Login in Heroku container registry
        run: heroku container:login
      - name: Push image to Heroku Registry
        run: docker push registry.heroku.com/$HEROKU_APP/web

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [publish_in_heroku_registry]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login in Heroku
        run: heroku container:login
      - name: Login in Heroku
        run: heroku container:release web

  smoke_test:
    name: Smoke test
    runs-on: ubuntu-latest
    needs: [deploy_to_heroku]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build native with Maven
        run: mvn -B -Dhost=${{ secrets.HEROKU_APP }}.herokuapp.com -Dtest=SeleniumTest test