name: Nightly workflow

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:
  build:
    name: Build Java application and run test
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run unitary test
      run: mvn -B -Dtest=BookServiceUnitaryTest test
    - name: Run REST test
      run: mvn -B -Dtest=RestTest test
    - name: Run e2e test
      run: mvn -B -Dtest=SeleniumTest test
    - name: Build native with Maven
      run: mvn -B package -DskipTests
    - name: Upload jar for next job
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  
  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Download Jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d.%H%M%S')
        id: project
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/library:dev-${{ steps.project.outputs.tag }} .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/library:dev-${{ steps.project.outputs.tag }}
