name: Develop workflow

on:
  push:
    branches: [ rama-pruebas ]

jobs:
  test-all:
    name: Build Java application and run test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run e2e test
      run: mvn -B -Dtest=SeleniumTest test
