name: CI-Develop-Feature

on:
  pull_request:
    branches: 
      - develop
      
  push: 
    branches: 
      - 'release/**'

jobs:
  test-unitary-rest:
    name: Run unitary and rest test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run unitary test
      run: mvn -B -Dtest=BookServiceUnitaryTest test
    - name: Run REST test
      run: mvn -B -Dtest=RestTest test
